console.log(
  JSON.parse(
    ' [{"question":"What is the recommended number of box size options for a typical retailer?","answers":[{"answer":"1","isCorrect":"false"},{"answer":"3-5","isCorrect":"true"},{"answer":"50","isCorrect":"false"}]},{"question":"What is the main factor to consider when choosing packaging material?","answers":[{"answer":"Cost","isCorrect":"false"},{"answer":"Protection","isCorrect":"true"},{"answer":"Weight","isCorrect":"true"}]},{"question":"What is the first step in optimising warehouse operations?","answers":[{"answer":"Arranging the warehouse","isCorrect":"true"},{"answer":"Improving KPIs","isCorrect":"false"},{"answer":"Replacing staff with software","isCorrect":"false"}]}]'
  )
)

// " [{\"topics\":[{\"topic\":\"Warehouse Management\"},{\"topic\":\"ABC Analysis\"},{\"topic\":\"Optimal Warehouse Arrangement\"},{\"topic\":\"Labelling\"},{\"topic\":\"Packing\"},{\"topic\":\"Integrations\"},{\"topic\":\"Reporting and Accountability\"}]}]"
// " [{\"question\":\"What is the recommended number of box size options for a typical retailer?\",\"answers\":[{\"answer\":\"1\",\"isCorrect\":\"false\"},{\"answer\":\"3-5\",\"isCorrect\":\"true\"},{\"answer\":\"50\",\"isCorrect\":\"false\"}]},{\"question\":\"What is the main factor to consider when choosing packaging material?\",\"answers\":[{\"answer\":\"Cost\",\"isCorrect\":\"false\"},{\"answer\":\"Protection\",\"isCorrect\":\"true\"},{\"answer\":\"Weight\",\"isCorrect\":\"true\"}]},{\"question\":\"What is the first step in optimising warehouse operations?\",\"answers\":[{\"answer\":\"Arranging the warehouse\",\"isCorrect\":\"true\"},{\"answer\":\"Improving KPIs\",\"isCorrect\":\"false\"},{\"answer\":\"Replacing staff with software\",\"isCorrect\":\"false\"}]}]"
// " [{\"summary\":[{\"paragraph\":\"Receiving and managing new stock is a critical part of warehouse management. It is important to have enough space in the receiving area to temporarily house newly delivered stock without risk of damage and for the team to perform necessary tasks. It is also important to record relevant details such as exact timestamps of when new stock arrives and is put away, and to make sure it is dealt with as soon as possible. Additionally, stock levels should be correctly updated on each sales channel or inventory management system, and any necessary labelling or barcodes should be added before physically putting the stock away.\"},{\"paragraph\":\"A mobile scanner device can make the booking in process much quicker and more accurate. It is also important to track KPIs such as receiving efficiency, rate of return, picking accuracy, and order lead time in order to measure the success of the warehouse management process.\"}]\n}]"
